@url=http://localhost:3000/api
@tokenUser=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidXNlcm5hbWUiOiJ1c2VyMSIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNjI5NzU5NzIwfQ.W7RnvU9NkH05GrP8wi05JIqGziTVVVodscTgaKBHI1M
@tokenAdmin=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJBRE1JTklTVFJBRE9SIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNjI5NzU5NTg0fQ.RKg3q-Zkzyhcz7LcIazZXYGhJJtgRoh4pMtURyeLjhg

###
post {{url}}/register
Content-Type: application/json

{
    "username": "user8",
    "nameSurname": "user1",
    "email": "user1@hotmail.com",
    "telephone": "21354548",
    "address": "san martin 452",
    "password": "12345Us#"
}

###
post {{url}}/login
Content-Type: application/json

{
    "username": "user1",
    "email": "user1@hotmail.com",
    "password": "12345Us#"
}

###
PUT {{url}}/register
Content-Type:  application/json
Authorization: {{tokenUser}}


{
    "nameSurname": "user modificado8",
    "email": "user1@hotmail.com",
    "telephone": "21354548",
    "address": "san martin 452",
    "password": "12345Us#"
}

###
GET {{url}}/register
Content-Type:  application/json
Authorization: {{tokenUser}}

###
GET {{url}}/products

###
POST {{url}}/orders
Content-Type:  application/json
Authorization: {{tokenUser}}


{
    "payment_type": "tarjeta",
    "order":[
        {
         "product_ID": 8,
         "amount": 1  
        },
        {
         "product_ID": 4,
         "amount": 2  
        },
        {
         "product_ID": 9,
         "amount": 3  
        }
    ]
}

###
GET {{url}}/order/52
Content-Type:  application/json
Authorization: {{tokenUser}}

###
PUT {{url}}/admin
Content-Type:  application/json
Authorization: {{tokenAdmin}}


{
    "nameSurname": "ADMINISTRADOR",
    "email": "user1@hotmail.com",
    "telephone": "21354548",
    "address": "san martin 452",
    "password": "12345Us##"
}

###
GET {{url}}/ordersAdmin
Content-Type:  application/json
Authorization: {{tokenAdmin}}

### 
GET {{url}}/orderAdmin
Content-Type:  application/json
Authorization: {{tokenAdmin}}

###
PUT {{url}}/ordersAdmin/69
Content-Type:  application/json
Authorization: {{tokenAdmin}}


{
    "state": "PREPARANDO"
}

###
DELETE {{url}}/ordersAdmin/52
Content-Type:  application/json
Authorization: {{tokenAdmin}}

###
POST {{url}}/productsAdmin
Content-Type:  application/json
Authorization: {{tokenAdmin}}

{
    "product_name": "LOMITO",
    "price": 750,
    "image":""
}

###
PUT {{url}}/productsAdmin/8
Content-Type:  application/json
Authorization: {{tokenAdmin}}

{
    "product_name": "hamburguesa",
    "price": 550,
    "image":""
}

###
DELETE {{url}}/productsAdmin/7
Content-Type:  application/json
Authorization: {{tokenAdmin}}

###
GET {{url}}/usersAdmin
Content-Type:  application/json
Authorization: {{tokenAdmin}}